# Generated by Django 5.0.1 on 2024-02-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_order_food_numper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_food',
            name='numPer',
        ),
    ]
