# Generated by Django 5.0.1 on 2024-02-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_order_food_numper'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_food',
            name='numPer',
            field=models.TextField(default=1),
        ),
    ]
